language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
env:
  - JRUBY_OPTS="--server -Xcext.enabled=true -Xcompile.invokedynamic=false"
script: bundle exec rspec spec
